<template>
  <div class="min-h-screen p-6 bg-cyber-bg text-gray-100 flex flex-col font-sans">
    <header class="mb-8 border-b border-gray-800 pb-4 flex justify-between items-center">
      <div>
        <h1 class="text-3xl font-mono text-cyber-cyan font-bold tracking-tight flex items-center gap-3">
          <img src="/icon.svg" class="w-8 h-8 drop-shadow-[0_0_10px_#00F0FF]" alt="Logo" /> QUANTUM <span class="text-cyber-magenta">MOCK</span>
        </h1>
        <p class="text-gray-400 mt-2 text-sm">Extreme Productivity Mocking Engine</p>
      </div>

      <div class="flex gap-4 items-center">
        <!-- Export / Import -->
        <div class="flex gap-2">
          <button @click="exportHub" class="text-xs px-3 py-2 bg-blue-500/10 text-blue-400 border border-blue-500/30 rounded hover:bg-blue-500 hover:text-white transition shadow-[0_0_10px_rgba(59,130,246,0.1)]">Export Config</button>
          <button @click="showImport = true" class="text-xs px-3 py-2 bg-green-500/10 text-green-400 border border-green-500/30 rounded hover:bg-green-500 hover:text-white transition shadow-[0_0_10px_rgba(34,197,94,0.1)]">Import Config</button>
        </div>

        <!-- Shadow Recording -->
        <label class="flex items-center gap-3 cursor-pointer bg-black/50 border border-gray-700 px-4 py-2 rounded-lg hover:border-cyber-magenta transition shadow-inner">
          <span class="text-sm font-bold flex items-center gap-2" :class="isRecording ? 'text-cyber-magenta' : 'text-gray-500'">
            <span class="w-3 h-3 rounded-full" :class="isRecording ? 'bg-cyber-magenta animate-pulse shadow-[0_0_10px_#FF003C]' : 'bg-gray-600'"></span> 
            SHADOW RECORDING
          </span>
          <input type="checkbox" v-model="isRecording" @change="toggleRecording" class="accent-cyber-magenta w-5 h-5 ml-2">
        </label>
      </div>
    </header>

    <!-- Import Modal -->
    <div v-if="showImport" class="fixed inset-0 bg-black/80 flex items-center justify-center z-50 backdrop-blur-sm">
      <div class="bg-cyber-bg border border-cyber-cyan p-6 rounded-lg w-1/2 shadow-[0_0_30px_rgba(0,240,255,0.2)]">
        <h3 class="text-xl font-bold text-cyber-cyan mb-4">📥 Import Remote Config</h3>
        <p class="text-sm text-gray-400 mb-2">Paste the Base64 code generated by a teammate to instantly inject their mock environment.</p>
        <textarea v-model="importData" class="w-full h-32 bg-black/50 border border-gray-700 rounded p-2 text-xs font-mono text-gray-300 focus:border-cyber-cyan mb-4 resize-none" placeholder="eJyrVkrLz..."></textarea>
        <div class="flex justify-end gap-2">
          <button @click="showImport = false; importData = ''" class="px-4 py-2 bg-gray-800 text-white rounded hover:bg-gray-700">Cancel</button>
          <button @click="importHub" class="px-4 py-2 bg-cyber-cyan text-black font-bold rounded hover:shadow-[0_0_15px_rgba(0,240,255,0.5)] transition">Inject Rules</button>
        </div>
      </div>
    </div>

    <!-- Export Toast -->
    <div v-if="exportToast" class="fixed top-6 right-6 bg-green-500 text-black px-4 py-2 rounded font-bold shadow-[0_0_15px_rgba(74,222,128,0.5)] z-50 animate-bounce">
      ✓ Config Code copied to clipboard!
    </div>

    <main class="flex-1 flex gap-6 min-h-0">
      <!-- Left Panel: Rules List -->
      <aside class="w-1/3 flex flex-col gap-4">
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-3">
            <h2 class="text-xl font-semibold text-white">Rules</h2>
            <button v-if="selectedIds.length > 0" @click="deleteSelected" class="px-2 py-1 text-xs font-bold bg-red-500/20 text-red-400 border border-red-500/50 rounded hover:bg-red-500 hover:text-white transition">
              Delete ({{ selectedIds.length }})
            </button>
          </div>
          <div class="flex gap-2 items-center">
             <button v-if="rules.length > 0" @click="selectAll" class="px-2 py-1 text-xs font-bold bg-cyber-magenta/20 text-cyber-magenta border border-cyber-magenta/50 rounded hover:bg-cyber-magenta hover:text-white transition">Select All</button>
             <button @click="createNewRule" class="px-3 py-1 bg-cyber-cyan/20 text-cyber-cyan border border-cyber-cyan/50 rounded hover:bg-cyber-cyan hover:text-black transition">
               + New
             </button>
          </div>
        </div>
        
        <div class="flex-1 overflow-y-auto pr-2 custom-scrollbar relative">
          <div v-if="rules.length === 0" class="text-sm text-gray-500 text-center py-8 border border-dashed border-gray-800 rounded">
            No rules yet. Create one or start recording.
          </div>
          
          <div v-for="(paths, method) in groupedRules" :key="method" class="mb-6">
            <h3 class="text-base font-bold mb-2 tracking-widest sticky top-0 bg-cyber-bg/95 backdrop-blur py-2 z-10" :class="getMethodTextColor(method as string)">
              {{ method }} ({{ Object.values(paths).flat().length }})
            </h3>
            <div class="space-y-4">
              <div v-for="(groupRules, path) in paths" :key="path" class="border-l-2 border-gray-700 pl-3 ml-1">
                <div class="text-sm text-gray-300 font-bold font-mono mb-2 truncate bg-gray-900/50 py-1 px-2 rounded w-fit" :title="path as string">{{ path }}/*</div>
                <div class="space-y-2">
                  <div v-for="rule in groupRules" :key="rule.id" 
                       @click="selectRule(rule)"
                       class="p-3 rounded bg-cyber-panel border cursor-pointer transition flex items-start gap-3 hover:bg-gray-800"
                       :class="selectedRule?.id === rule.id ? 'border-cyber-cyan shadow-[0_0_15px_rgba(0,240,255,0.3)]' : 'border-gray-700'">
                    
                    <input type="checkbox" :value="rule.id" v-model="selectedIds" @click.stop class="accent-red-500 w-5 h-5 mt-1 cursor-pointer">

                    <div class="flex-1 min-w-0">
                      <div class="flex justify-between items-center mb-1">
                        <span class="font-mono text-base font-bold truncate flex items-center gap-2" :class="rule.active ? 'text-cyber-cyan' : 'text-gray-500'">
                          {{ rule.name }}
                          <span class="text-[10px] px-1.5 py-0.5 rounded-full font-bold shadow-[0_0_8px_rgba(0,240,255,0.4)] bg-cyber-cyan text-black leading-none" title="Times intercepted">
                            {{ rule.interceptCount || 0 }}
                          </span>
                        </span>
                        
                        <label class="relative inline-flex items-center cursor-pointer ml-2" @click.stop>
                          <input type="checkbox" v-model="rule.active" @change="saveRule(rule)" class="sr-only peer">
                          <div class="w-10 h-5 bg-gray-800 border-gray-600 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-gray-500 peer-checked:after:bg-cyber-cyan after:border-gray-300 after:border after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-cyber-cyan/20 peer-checked:border-cyber-cyan border peer-checked:shadow-[0_0_8px_rgba(0,240,255,0.5)]"></div>
                        </label>

                      </div>
                      <div class="text-sm text-gray-400 truncate flex items-center gap-1">
                        <span class="truncate" :title="rule.urlPattern">{{ rule.urlPattern.replace(path as string, '') || '/' }}</span>
                      </div>
                      <div class="mt-2 flex gap-2">
                        <span v-if="rule.responses.length > 1" class="text-xs text-cyber-cyan font-bold border border-cyber-cyan/50 px-2 py-0.5 rounded bg-cyber-cyan/10">State {{ (rule.activeResponseIndex || 0) + 1 }}/{{rule.responses.length}}</span>
                        <span v-if="rule.responses[rule.activeResponseIndex || 0]?.simulateNetworkError" class="text-xs text-cyber-magenta font-bold border border-cyber-magenta/50 px-2 py-0.5 rounded bg-cyber-magenta/10">ERR</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </aside>

      <!-- Right Panel: Master-Detail -->
      <section class="flex-1 bg-cyber-panel border border-gray-800 rounded-lg p-5 flex flex-col min-h-0" v-if="selectedRule">
        <div class="flex justify-between items-center mb-4">
          <input v-model="selectedRule.name" class="bg-transparent border-b border-gray-700 text-xl font-bold text-white focus:outline-none focus:border-cyber-cyan pb-1 w-1/3" placeholder="Rule Name">
          
          <div v-if="selectedRule.capturedTraffic" class="flex bg-black/50 border border-gray-700 rounded overflow-hidden">
            <button @click="rightPanelMode = 'editor'" class="px-4 py-1 text-xs font-bold transition" :class="rightPanelMode === 'editor' ? 'bg-cyber-cyan text-black' : 'text-gray-500 hover:text-white'">Mock Editor</button>
            <button @click="rightPanelMode = 'inspector'" class="px-4 py-1 text-xs font-bold transition flex gap-2 items-center" :class="rightPanelMode === 'inspector' ? 'bg-cyber-magenta text-white shadow-[0_0_10px_#FF003C]' : 'text-gray-500 hover:text-white'">
              <span class="animate-pulse">🔴</span> Inspector
            </button>
          </div>

          <button @click="saveRule(selectedRule)" class="px-6 py-2 text-black font-bold rounded transition" :class="isSaving ? 'bg-green-400 shadow-[0_0_15px_rgba(74,222,128,0.5)]' : 'bg-cyber-cyan hover:shadow-[0_0_15px_rgba(0,240,255,0.5)]'">
            {{ isSaving ? '✓ Saved!' : 'Save Rule' }}
          </button>
        </div>

        <!-- INSPECTOR VIEW -->
        <div v-if="rightPanelMode === 'inspector' && selectedRule.capturedTraffic" class="flex-1 flex flex-col min-h-0 bg-black/40 border border-gray-800 rounded-lg p-4">
          <div class="flex gap-2 mb-4 border-b border-gray-800 pb-2 overflow-x-auto custom-scrollbar">
            <button v-for="tab in inspectorTabs" :key="tab.id" @click="inspectorTab = tab.id" class="px-3 py-1.5 text-xs font-bold rounded transition whitespace-nowrap" :class="inspectorTab === tab.id ? 'bg-cyber-magenta text-white shadow-[0_0_10px_rgba(255,0,60,0.5)]' : 'text-gray-500 hover:text-gray-300 hover:bg-gray-800'">
              {{ tab.label }}
            </button>
          </div>
          <div class="flex-1 min-h-0 relative">
            <component 
              :is="activeInspectorComponent" 
              v-bind="inspectorProps" 
              @show-tooltip="onShowTooltip"
              @hide-tooltip="onHideTooltip"
            />
          </div>
        </div>

        <!-- EDITOR VIEW -->
        <div v-show="rightPanelMode === 'editor'" class="flex-1 flex flex-col min-h-0">

        <div class="grid grid-cols-2 gap-4 mb-4">
          <div>
            <label class="block text-xs text-gray-400 mb-1">URL Pattern (Regex or *)</label>
            <input v-model="selectedRule.urlPattern" class="w-full bg-black/50 border border-gray-700 rounded p-2 text-sm font-mono focus:border-cyber-cyan focus:outline-none">
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-xs text-gray-400 mb-1">Method</label>
              <CyberSelect 
                v-model="selectedRule.method" 
                :options="['GET','POST','PUT','DELETE','PATCH','OPTIONS','ANY']" 
                :colorClass="getMethodTextColor(selectedRule.method)" 
              />
            </div>
            <div>
              <label class="block text-xs text-gray-400 mb-1">Priority <span class="text-gray-500">(Higher wins)</span></label>
              <input type="number" v-model.number="selectedRule.priority" class="w-full bg-black/50 border border-gray-700 rounded p-2 text-sm focus:border-cyber-cyan focus:outline-none">
            </div>
          </div>
        </div>

        <!-- ACTIVE STATES MANUAL SELECTOR -->
        <div class="mt-2 mb-2 flex items-center border-b-2 border-gray-800 overflow-x-auto overflow-y-hidden select-none pt-2 relative">
          <div class="text-[10px] text-gray-500 font-bold uppercase tracking-wider mr-4 ml-1">Mock States</div>
          <button v-for="(res, idx) in selectedRule.responses" :key="idx"
                  @click="switchState(idx)"
                  class="px-5 py-2 text-xs font-bold rounded-t-lg transition flex items-center gap-2 relative z-10 border-l border-r border-t"
                  :class="(selectedRule.activeResponseIndex || 0) === idx ? 'bg-cyber-panel text-cyber-cyan border-t-2 border-t-cyber-cyan border-l-gray-700 border-r-gray-700 border-b-cyber-panel shadow-[0_-5px_15px_rgba(0,240,255,0.1)] translate-y-[2px]' : 'bg-black/30 border-gray-800/50 text-gray-500 hover:text-gray-300 hover:bg-gray-800'">
            State {{ idx + 1 }}
            <span v-if="(selectedRule.activeResponseIndex || 0) === idx" class="bg-cyber-cyan text-black px-1.5 py-0.5 rounded text-[8px] tracking-widest font-black shadow-[0_0_8px_#00F0FF]">ACTIVE</span>
            <span v-if="selectedRule.responses.length > 1 && (selectedRule.activeResponseIndex || 0) !== idx" @click.stop="removeState(idx)" class="text-red-500 hover:text-red-400 hover:scale-125 transition ml-1">×</span>
          </button>
          <button @click="addState" class="px-3 py-1.5 text-xs font-bold rounded-t-lg text-cyber-cyan hover:bg-cyber-cyan/10 ml-2 border border-dashed border-cyber-cyan/50 opacity-70 hover:opacity-100">+ Add State</button>
        </div>
        <div class="text-[10px] text-cyber-cyan/70 mb-4 bg-cyber-cyan/10 px-3 py-1 rounded border border-cyber-cyan/20 flex gap-2 items-center">
          <span class="animate-pulse">👁️</span> The interceptor will <strong>always</strong> return the Active State for this rule.
        </div>

        <template v-if="selectedRule.responses[selectedRule.activeResponseIndex || 0]">
          <div class="grid grid-cols-3 gap-4 mb-4 items-start">
            <div>
              <label class="block text-xs text-gray-400 mb-1">Status Code</label>
              <StatusCodeSelect 
                v-model="selectedRule.responses[selectedRule.activeResponseIndex || 0].status" 
                :disabled="selectedRule.responses[selectedRule.activeResponseIndex || 0].simulateNetworkError"
              />
            </div>
            <div>
              <label class="block text-xs text-gray-400 mb-1">Response Type</label>
              <CyberSelect 
                v-model="selectedRule.responses[selectedRule.activeResponseIndex || 0].responseType" 
                :options="['application/json', 'text/plain', 'text/html']"
                :disabled="selectedRule.responses[selectedRule.activeResponseIndex || 0].simulateNetworkError"
              />
            </div>
            <div>
              <label class="block text-xs text-gray-400 mb-1">Latency (ms)</label>
              <input type="number" v-model.number="selectedRule.responses[selectedRule.activeResponseIndex || 0].delayMs" class="w-full bg-black/50 border border-gray-700 rounded p-2 text-sm focus:border-cyber-cyan focus:outline-none mb-1">
              <div class="flex gap-1">
                <button @click="selectedRule.responses[selectedRule.activeResponseIndex || 0].delayMs = 0" class="flex-1 text-[10px] py-1 bg-gray-800 rounded hover:bg-cyber-cyan hover:text-black">0s</button>
                <button @click="selectedRule.responses[selectedRule.activeResponseIndex || 0].delayMs = 1000" class="flex-1 text-[10px] py-1 bg-gray-800 rounded hover:bg-cyber-cyan hover:text-black">1s</button>
                <button @click="selectedRule.responses[selectedRule.activeResponseIndex || 0].delayMs = 5000" class="flex-1 text-[10px] py-1 bg-gray-800 rounded hover:bg-cyber-cyan hover:text-black">5s</button>
                <button @click="selectedRule.responses[selectedRule.activeResponseIndex || 0].delayMs = 10000" class="flex-1 text-[10px] py-1 bg-gray-800 rounded hover:bg-cyber-cyan hover:text-black">10s</button>
              </div>
            </div>
          </div>

          <div class="mb-4">
            <label class="flex items-center gap-2 cursor-pointer bg-red-500/10 border border-red-500/30 p-2 rounded hover:bg-red-500/20 transition w-max">
              <input type="checkbox" v-model="selectedRule.responses[selectedRule.activeResponseIndex || 0].simulateNetworkError" class="accent-cyber-magenta w-4 h-4">
              <span class="text-sm font-bold text-cyber-magenta">Simulate Network Error (Failed to fetch)</span>
            </label>
          </div>

          <div class="flex-1 flex flex-col min-h-[100px]" :class="selectedRule.responses[selectedRule.activeResponseIndex || 0].simulateNetworkError ? 'opacity-30 pointer-events-none' : ''">
            <div class="flex justify-between items-center mb-1">
              <div class="flex items-center gap-4">
                <label class="text-xs text-gray-400">Response Body - State {{ (selectedRule.activeResponseIndex || 0) + 1 }}</label>
              </div>
              <button v-if="parsedJsonBody" @click="jsonViewMode = !jsonViewMode" class="text-[10px] px-2 py-1 rounded border transition" :class="jsonViewMode ? 'bg-cyber-cyan text-black border-cyber-cyan shadow-[0_0_10px_rgba(0,240,255,0.4)]' : 'bg-black text-gray-400 border-gray-700 hover:text-white'">
                {{ jsonViewMode ? 'View Mode Active' : 'Enable JSON Viewer' }}
              </button>
            </div>
            
            <!-- JSON Viewer Mode -->
            <div v-if="jsonViewMode && parsedJsonBody" class="flex-1 overflow-auto bg-black border border-gray-700 rounded p-4 shadow-inner custom-scrollbar">
               <JsonViewer :data="parsedJsonBody" />
            </div>
            
            <!-- Raw Editor Mode -->
            <textarea v-else v-model="selectedRule.responses[selectedRule.activeResponseIndex || 0].body" class="flex-1 w-full bg-black/80 border rounded p-3 text-sm font-mono focus:outline-none resize-none shadow-inner custom-scrollbar text-gray-300 border-gray-700 focus:border-cyber-cyan" placeholder='{"success": true}'></textarea>
          </div>
        </template>
        </div>
      </section>
      
      <!-- Placeholder when no rule selected -->
      <section class="flex-1 bg-cyber-panel border border-gray-800 rounded-lg flex items-center justify-center text-gray-500 flex-col gap-4" v-else>
        <div class="text-6xl opacity-20">⚡</div>
        <p>Select a rule to edit or inspect</p>
      </section>
    </main>

    <!-- GLOBAL TOOLTIP -->
    <div v-if="tooltipState.visible" 
         class="fixed pointer-events-none z-50 backdrop-blur-md bg-black/80 border border-cyber-cyan shadow-[0_0_20px_#00F0FF] p-4 rounded-lg w-64 text-sm transition-opacity duration-200"
         :style="{ left: tooltipState.x + 15 + 'px', top: tooltipState.y + 15 + 'px' }">
      <h4 class="text-cyber-cyan font-bold mb-1 uppercase text-xs">{{ tooltipState.title }}</h4>
      <p class="text-gray-300 text-xs">{{ tooltipState.desc }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue';
import { db } from '../../db/db';
import InspectorDictView from './components/InspectorDictView.vue';
import InspectorPayload from './components/InspectorPayload.vue';
import type { MockRule } from '../../schema/mockRule';
import JsonViewer from './components/JsonViewer.vue';
import StatusCodeSelect from './components/StatusCodeSelect.vue';
import CyberSelect from './components/CyberSelect.vue';

const rules = ref<MockRule[]>([]);
const selectedRule = ref<MockRule | null>(null);
const selectedIds = ref<string[]>([]);
const isSaving = ref(false);
const isRecording = ref(false);
const jsonViewMode = ref(false);

const rightPanelMode = ref<'editor' | 'inspector'>('editor');
const inspectorTab = ref('reqPayload');

const inspectorTabs = [
  { id: 'reqPayload', label: 'Request Payload' },
  { id: 'resPayload', label: 'Response Payload' },
  { id: 'reqHeaders', label: 'Request Headers' },
  { id: 'resHeaders', label: 'Response Headers' },
  { id: 'cookies', label: 'Cookies' }
];

const tooltipState = ref({
  visible: false,
  x: 0,
  y: 0,
  title: '',
  desc: ''
});

const onShowTooltip = ({ entry, event }: any) => {
  tooltipState.value = {
    visible: true,
    x: event.clientX,
    y: event.clientY,
    title: entry.title,
    desc: entry.desc
  };
};

const onHideTooltip = () => {
  tooltipState.value.visible = false;
};

const activeInspectorComponent = computed(() => {
  if (inspectorTab.value.includes('Payload')) return InspectorPayload;
  return InspectorDictView;
});

const inspectorProps = computed(() => {
  const traffic = selectedRule.value?.capturedTraffic;
  if (!traffic) return { title: 'No Data' };
  
  switch(inspectorTab.value) {
    case 'reqPayload': return { title: 'Request Payload', body: traffic.requestBody || '' };
    case 'resPayload': return { title: 'Response Payload', body: selectedRule.value?.responses[0]?.body || '' };
    case 'reqHeaders': return { title: 'Request Headers', data: traffic.requestHeaders || {} };
    case 'resHeaders': return { title: 'Response Headers', data: traffic.responseHeaders || {} };
    case 'cookies': return { title: 'Cookies', data: traffic.cookies || {} };
    default: return { title: 'Unknown' };
  }
});

const groupedRules = computed(() => {
  const groups: Record<string, Record<string, MockRule[]>> = {};
  const order = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'ANY'];
  
  for (const rule of rules.value) {
    if (!groups[rule.method]) groups[rule.method] = {};
    
    let rawUrl = rule.urlPattern?.trim() || '';
    let basePath = rawUrl.split('?')[0];
    
    if (basePath !== '*' && basePath !== '.*' && basePath !== '') {
      try {
        if (basePath.startsWith('http')) {
          const u = new URL(basePath);
          const parts = u.pathname.split('/').filter(Boolean);
          const groupSegments = parts.slice(0, 2);
          basePath = u.origin + (groupSegments.length ? '/' + groupSegments.join('/') : '');
        } else {
          const parts = basePath.split('/').filter(Boolean);
          const groupSegments = parts.slice(0, 2);
          basePath = groupSegments.length ? '/' + groupSegments.join('/') : basePath;
        }
      } catch(e) {
        const parts = basePath.split('/');
        basePath = parts.slice(0, 3).join('/');
      }
    }
    
    if (!groups[rule.method][basePath]) groups[rule.method][basePath] = [];
    groups[rule.method][basePath].push(rule);
  }
  
  const sortedGroups: Record<string, Record<string, MockRule[]>> = {};
  order.forEach(method => {
    if (groups[method]) sortedGroups[method] = groups[method];
  });
  
  return sortedGroups;
});

const parsedJsonBody = computed(() => {
  if (!selectedRule.value) return null;
  const activeRes = selectedRule.value.responses[selectedRule.value.activeResponseIndex || 0];
  if (!activeRes || !activeRes.body) return null;
  try {
    return JSON.parse(activeRes.body);
  } catch {
    return null;
  }
});

watch(parsedJsonBody, (newVal) => {
  if (newVal === null && jsonViewMode.value) {
    jsonViewMode.value = false;
  }
});

const showImport = ref(false);
const importData = ref('');
const exportToast = ref(false);

const loadRules = async () => {
  const rawRules = await db.mockRules.toArray();
  const migratedRules: MockRule[] = [];
  
  for (const r of rawRules) {
    if (!r.responses && (r as any).response) {
      r.responses = [{
        ...((r as any).response),
        delayMs: (r as any).delayMs || 0,
        simulateNetworkError: (r as any).simulateNetworkError || false
      }];
      delete (r as any).response;
      delete (r as any).delayMs;
      delete (r as any).simulateNetworkError;
      r.activeResponseIndex = 0;
      await db.mockRules.put(r);
    }
    if (r.activeResponseIndex === undefined) {
      r.activeResponseIndex = 0;
    }
    migratedRules.push(r as MockRule);
  }
  
  rules.value = migratedRules;
};

const loadRecordingState = async () => {
  const result = await chrome.storage.local.get('isRecording');
  isRecording.value = !!result.isRecording;
};

const toggleRecording = async () => {
  await chrome.storage.local.set({ isRecording: isRecording.value });
};

onMounted(() => {
  loadRules();
  loadRecordingState();
});

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === 'local' && changes.isRecording) {
    isRecording.value = !!changes.isRecording.newValue;
  }
});

chrome.runtime.onMessage.addListener((msg) => {
  if (msg.type === 'RULES_UPDATED') {
    loadRules();
  }
});

const notifyBackground = () => {
  chrome.runtime.sendMessage({ type: 'RULES_UPDATED' });
};

const createNewRule = () => {
  const newRule: MockRule = {
    id: crypto.randomUUID(),
    name: 'New Mock Rule',
    active: true,
    urlPattern: '*/api/test',
    method: 'GET',
    scenarioId: null,
    priority: 10,
    activeResponseIndex: 0,
    responses: [{
      status: 200,
      responseType: 'application/json',
      headers: {},
      body: '{\n  "message": "Hello from Quantum Mock!"\n}',
      delayMs: 0,
      simulateNetworkError: false
    }]
  };
  rules.value.unshift(newRule);
  selectedRule.value = newRule;
};

const switchState = async (idx: number) => {
  if (!selectedRule.value) return;
  selectedRule.value.activeResponseIndex = idx;
  await saveRule(selectedRule.value);
};

const addState = async () => {
  if (!selectedRule.value) return;
  const lastState = selectedRule.value.responses[selectedRule.value.responses.length - 1];
  selectedRule.value.responses.push(JSON.parse(JSON.stringify(lastState)));
  selectedRule.value.activeResponseIndex = selectedRule.value.responses.length - 1;
  await saveRule(selectedRule.value);
};

const removeState = async (idx: number) => {
  if (!selectedRule.value) return;
  if (selectedRule.value.responses.length <= 1) return;
  selectedRule.value.responses.splice(idx, 1);
  if ((selectedRule.value.activeResponseIndex || 0) >= selectedRule.value.responses.length) {
    selectedRule.value.activeResponseIndex = selectedRule.value.responses.length - 1;
  }
  await saveRule(selectedRule.value);
};

const saveRule = async (rule: MockRule) => {
  await db.mockRules.put(JSON.parse(JSON.stringify(rule)));
  await loadRules();
  notifyBackground();
  
  isSaving.value = true;
  setTimeout(() => {
    isSaving.value = false;
  }, 1200);
};

const selectRule = (rule: MockRule) => {
  if (selectedRule.value && rule.id === selectedRule.value.id) return;
  selectedRule.value = { ...rule };
  rightPanelMode.value = 'editor';
  if (selectedRule.value.capturedTraffic) {
    inspectorTab.value = 'reqPayload';
  }
};

const selectAll = () => {
  if (selectedIds.value.length === rules.value.length) {
    selectedIds.value = [];
  } else {
    selectedIds.value = rules.value.map(r => r.id);
  }
};

const deleteSelected = async () => {
  if (selectedIds.value.length === 0) return;
  await db.mockRules.bulkDelete(selectedIds.value);
  
  if (selectedRule.value && selectedIds.value.includes(selectedRule.value.id)) {
    selectedRule.value = null;
  }
  
  selectedIds.value = [];
  await loadRules();
  notifyBackground();
};

const exportHub = () => {
  try {
    const payload = JSON.stringify(rules.value);
    const base64 = btoa(unescape(encodeURIComponent(payload)));
    navigator.clipboard.writeText(base64);
    exportToast.value = true;
    setTimeout(() => { exportToast.value = false; }, 3000);
  } catch(e) {
    alert("Failed to export rules.");
  }
};

const importHub = async () => {
  if (!importData.value) return;
  try {
    const jsonStr = decodeURIComponent(escape(atob(importData.value.trim())));
    const importedRules: MockRule[] = JSON.parse(jsonStr);
    
    for (const r of importedRules) {
      r.id = crypto.randomUUID(); 
      await db.mockRules.put(r);
    }
    
    await loadRules();
    notifyBackground();
    showImport.value = false;
    importData.value = '';
    alert(`Successfully injected ${importedRules.length} rules!`);
  } catch (e) {
    alert("Invalid Config Code. Ensure you copied the full Base64 string.");
  }
};

const getMethodTextColor = (method: string) => {
  switch(method) {
    case 'GET': return 'text-blue-400';
    case 'POST': return 'text-green-400';
    case 'PUT': return 'text-yellow-400';
    case 'PATCH': return 'text-orange-400';
    case 'DELETE': return 'text-red-400';
    case 'ANY': return 'text-purple-400';
    default: return 'text-gray-400';
  }
};
</script>
